let current=0,score=0,attempted=0,correct=0,locked=false,timeLeft=1800,timerId=null;const answered=new Map(),bookmarks=new Set(),fiftyUsed=new Set();const $=id=>document.getElementById(id);
function topic(i){return i<15?'Meaning & Nature':i<30?'Teaching vs Learning':i<45?'Principles of Teaching':i<60?'Learner-Centred Education':i<75?'Teacher vs Learner-Centred':i<90?'Role of Teacher & Learner':'UPSC/KVS/NVS Case Studies'}
function render(){const q=QUESTIONS[current];locked=answered.has(current);$('counter').textContent=`Question ${current+1} of ${QUESTIONS.length}`;$('qno').textContent='Q'+(current+1);$('topic').textContent=topic(current);$('question').textContent=q.question;$('bar').style.width=((current+1)/QUESTIONS.length*100)+'%';$('bookmark').textContent=bookmarks.has(current)?'★ Bookmarked':'☆ Bookmark';$('bookmark').classList.toggle('booked',bookmarks.has(current));$('options').innerHTML='';q.options.forEach((o,i)=>{const b=document.createElement('button');b.className='option';b.dataset.letter=String.fromCharCode(65+i);b.textContent=o;b.onclick=()=>choose(i);if(locked){b.disabled=true;b.classList.add('disabled');if(i===q.answer)b.classList.add('correct');if(answered.get(current)!==q.answer&&i===answered.get(current))b.classList.add('wrong')}$('options').appendChild(b)});$('feedback').classList.toggle('hidden',!locked);if(locked){const selected=answered.get(current);const opts=q.options.map((o,i)=>{let cls='solution-option';let tag='';if(i===q.answer){cls+=' solution-correct';tag=' ✓ CORRECT ANSWER / सही उत्तर'}if(i===selected && i!==q.answer){cls+=' solution-wrong';tag=' ✗ YOUR ANSWER / आपका उत्तर'}return `<div class="${cls}"><span class="sol-letter">${String.fromCharCode(65+i)}</span><span>${o}</span><b>${tag}</b></div>`}).join('');$('feedback').innerHTML=`<div class="solution-title">📘 Options & Solution / विकल्प एवं समाधान</div>${opts}<div class="solution-explanation"><b>Explanation / व्याख्या:</b><br>${q.explanation}</div>`;}updateStats();buildPalette();$('prev').disabled=current===0;$('next').textContent=current===QUESTIONS.length-1?'Finish':'Next →'}
function choose(i){if(locked)return;const q=QUESTIONS[current];answered.set(current,i);attempted++;if(i===q.answer){score++;correct++}render()}
function updateStats(){$('correct').textContent=correct;$('attempted').textContent=attempted;$('accuracy').textContent=(attempted?Math.round(correct/attempted*100):0)+'%'}
function buildPalette(){const p=$('palette');p.innerHTML='';QUESTIONS.forEach((_,i)=>{const b=document.createElement('button');b.className='pbtn';b.textContent=i+1;if(i===current)b.classList.add('current');if(answered.has(i)){b.classList.add(answered.get(i)===QUESTIONS[i].answer?'done':'wrong')}if(bookmarks.has(i))b.classList.add('book');b.onclick=()=>{current=i;render()};p.appendChild(b)})}
function formatTime(){const m=Math.floor(timeLeft/60),s=timeLeft%60;$('timer').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');if(timeLeft<=60)$('timer').style.color='#ef4444'}
function startTimer(){clearInterval(timerId);formatTime();timerId=setInterval(()=>{timeLeft--;formatTime();if(timeLeft<=0){clearInterval(timerId);finish()}},1000)}
$('next').onclick=()=>{if(current<QUESTIONS.length-1){current++;render()}else finish()};$('prev').onclick=()=>{if(current>0){current--;render()}};$('bookmark').onclick=()=>{bookmarks.has(current)?bookmarks.delete(current):bookmarks.add(current);render()};
$('fifty').onclick=()=>{if(fiftyUsed.has(current)){alert('50:50 already used for this question.');return}fiftyUsed.add(current);const q=QUESTIONS[current];[...Array(4).keys()].filter(i=>i!==q.answer).sort(()=>Math.random()-.5).slice(0,2).forEach(i=>{$('options').children[i].disabled=true;$('options').children[i].classList.add('disabled')})};
$('poll').onclick=()=>{const q=QUESTIONS[current],raw=q.options.map((_,i)=>i===q.answer?58:14+Math.floor(Math.random()*8)),total=raw.reduce((a,b)=>a+b,0),pct=raw.map(v=>Math.round(v/total*100));$('modalContent').innerHTML='<h2>Audience Poll / ऑडियंस पोल</h2>'+pct.map((p,i)=>`<div><b>${String.fromCharCode(65+i)}</b> — ${p}%<div class="pollbar"><i style="width:${p}%"></i></div></div>`).join('');$('modal').classList.remove('hidden')};
$('expert').onclick=()=>{const q=QUESTIONS[current];$('modalContent').innerHTML='<h2>Ask the Expert / विशेषज्ञ से पूछें</h2><p><b>Best answer:</b> '+String.fromCharCode(65+q.answer)+'. '+q.options[q.answer]+'</p><p>'+q.explanation+'</p>';$('modal').classList.remove('hidden')};
$('reset').onclick=()=>{if(confirm('Restart the quiz?')){current=score=attempted=correct=0;timeLeft=1800;answered.clear();bookmarks.clear();fiftyUsed.clear();startTimer();render()}};function closeModal(){$('modal').classList.add('hidden')};function finish(){clearInterval(timerId);const pct=Math.round(correct/QUESTIONS.length*100);$('modalContent').innerHTML=`<h2>Quiz Completed 🎉</h2><p><b>Score:</b> ${correct}/${QUESTIONS.length}</p><p><b>Percentage:</b> ${pct}%</p><p><b>Attempted:</b> ${attempted}</p><p>${pct>=80?'🏆 Excellent preparation! / उत्कृष्ट तैयारी!':pct>=60?'👍 Good effort. Revise weak areas. / अच्छा प्रयास।':'📚 Keep practising and revise the concepts. / अभ्यास जारी रखें।'}</p><button onclick="closeModal();current=0;render()">Review Questions</button>`;$('modal').classList.remove('hidden')};
startTimer();render();
